version: '3'
services:

  frontend:
    image: ansism/frontend:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
    ports:
      - "8000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
