version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5556:5432"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mintos
      POSTGRES_DB: mintos
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: